spring.application.name=ResumePortfolio

server.servlet.context-path=/ResumePortfolio

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB

file.upload-dir=uploads/

spring.messages.encoding=UTF-8
spring.messages.basename=messages

logging.level.kr.pile.songwoo.resumeportfolio=INFO
logging.file.name=logs/resume-portfolio.log